### ISSUE TITLE
Support ffmpeg with proxy

### ISSUE THREAD

**Issue by tjeh** [Pavion/tvstreamrecord#11]
Hi, long time no see :)

could you add the possibility to set the environment variable "http_proxy" so that ffmpeg can use this when recording streams.

**Required changes**

*config.py*
* add proxy enable/disable button
* add proxy url field (which is only enabled, when "button" is enabled (like the postprocessing option)

*config.tpl*
* changes in UI to reflect new config variables

*tvstreamrecord.py*
* [doRecord](https://github.com/Pavion/tvstreamrecord/blob/master/tvstreamrecord.py#L930) needs to set  **os.environ["http_proxy"] = "http://127.0.0.1:8080"** prior to calling ffmpeg

I have tested recording using ffmpeg and a proxy sucessfully by just inserting the os.environment directly into the source code. However an integration into the tvstreamrecord UI would be a much "cleaner" solution.

**Comment by Pavion** [comment]
Erledigt. Teste bitte die aktuelle Version und schließe die Issue, wenn Du zufrieden warst.

**Comment by tjeh** [comment]
Funktioniert!
