### ISSUE TITLE
Issue with placeholder %title%

### ISSUE THREAD

**Issue by tjeh** [Pavion/tvstreamrecord#12]
Hi,

i am running tvstreamrecord on windows. Apparently when trying to record shows with a title containing  "ä,ö,ü" i.e. "Bares für Wahres" the recording fails. When i manually change the title for such recordings from ie. "ü" to "ue" the recording works without any issues.

I guess %title% placeholder is somehow escaped within the script and windows does not like the current implementation of how "ä,ö,ü" are handled. 

Furthermore excessive "spaces" in the shows title are each replaced with "_". This results sometimes in something like:
- "This is a Title   with" --> "This_is_a_Title___with"

regards

**Comment by Pavion** [comment]
Hallo Tjeh,

ich nehme an, dass es sich dabei nicht um den Platzhalter handelt, sondern um den Aufruf von ffmpeg. Schaue bitte, ob in Deinem Log so etwas steht: 
['ffmpeg', u'-i', 'http://192.168.0.20/blah', u'-y', u'-loglevel', u'fatal', u'-t', u'1102', '-acodec', 'copy', '-vcodec', 'copy', '-loglevel', 'info', u'd:\\20150902172037 - **\u0416\u0419\xc4\xf6.ts'**]
FFMPEG could not be started
Ich habe es jedenfalls so bei mir beobachtet und schaue jetzt nach einer Lösung. In Python 3 gibt es diesen Fehler übrigens nicht. 

Was die "_" angeht, so ist es an sich gewollt, zum großen Teil auch aus dem gleichen Grund wie oben. In Python 2.x ist die Handlung von Unicode eben extrem schwierig.

**Comment by Pavion** [comment]
Ebenfalls in der aktuellen Version gelöst. Da ich das Problem nicht zuverlässig lösen kann, musste ich leider durchgreifen. Bei der Kombination ffmpeg + Python 2.x ersetze ich nun alle Sonderzeichen ab ASCII 128 durch Unterstriche. Dafür funktioniert es zumindest. Bitte auch prüfen und schließen. 
Gruß
Pav

**Comment by tjeh** [comment]
Also hier mal ein Ausschnitt aus dem Logfile mit der Vorgängerversion:

[u'C:\\apps\\ffmpeg\\bin\\ffmpeg.exe', u'-i', 'http://pebbles106-lh.akamaihd.net/i/rtl_1@97459/master.m3u8', u'-y', u'-loglevel', u'fatal', u'-t', u'3075', u'-acodec', u'copy', u'-vcodec', u'copy', u'/inbox/iptv/Verdachtsf\xe4lle-20150902151144.ts']

**Comment by tjeh** [comment]
Die neue Version https://github.com/Pavion/tvstreamrecord/commit/e458359b0b812b8a8fc672f4e82777c2637c1767 funktioniert und führt zu folgendem Ergebnis:

[u'C:\\...\\ffmpeg.exe', u'-i', 'http://xxx', u'-y', u'-loglevel', u'fatal', u'-t', u'4592', u'-acodec', u'copy', u'-vcodec', u'copy', u'/inbox/iptv/Aktenzeichen_XY____ungel_st___Die_Kriminalpolizei_bittet_um_Mithilfe-20150902203127.ts']

Jetzt wäre es noch perfekt, wenn die "überschüssigen" Underscores durch jeweils nur einen ersetzt werden.

**Comment by Pavion** [comment]
Der Name der Sendung lautet: Aktenzeichen XY... ungelöst - Die Kriminalpolizei bittet um Hilfe
Alle Sonderzeichen wurden der Reihe nach durch Unterstriche ersetzt. Es sieht zwar nicht schön aus aber zumindest eindeutig. Striche dann zusammenzufassen würde den Text komplett seiner Lesbarkeit rauben. Für eine bessere Unicode-Unterstützung nutze bitte Python 3.x
