### ISSUE TITLE
extend available placeholders to enable multiple record directories

### ISSUE THREAD

**Issue by tjeh** [Pavion/tvstreamrecord#13]
Hi,
gerade wenn viel gleichzeitig aufgenommen wird, wäre es gut, wenn mehr Platzhalter zur Verfügung stehen würden:
- %month% , %year%, %day% ...
- %channel%
- %channelid%
- ...

Somit könnte man direkt bei der Aufnahme eine gewisse "Vorsortierung" (Dateiname und ggf. Ordner erstellen) auf Ordnerebene erreichen.

Oder.. beim Aufnahmedialog ein zusätzliches Felder ergänzen, dass diese Aufnahme in einen Unterordner im Standard Record Verzeichnis gespeichert wird. Das wäre sicherlich für wiederkehrende Aufnahmen interessant.

**Comment by Pavion** [comment]
Pfadangabe sowie besagte Platzhalter sind jetzt möglich. 
Bitte prüfen und schließen.
Gruß
Pav

**Comment by tjeh** [comment]
Platzhalter/Ordner funktionieren einwandfrei. Danke!

PS.: Test nur unter python3 durchgeführt.
