### ISSUE TITLE
Enhance Record Dialog

### ISSUE THREAD

**Issue by tjeh** [Pavion/tvstreamrecord#14]
Beim starten einer Aufnahme via "EPG Chart" wird nur "Record" und "Cancel" angeboten. 

Hier wäre es hilfreich, wenn ein "Record & Edit" verfügbar wäre. Somit könnten Titel und weitere Details direkt geändert werden ohne vorher auf den Reiter "Records" zu wechseln.

**Comment by Pavion** [comment]
Hallo Tjeh, 

mit dem letzten Commit sollte es funktionieren. Ich habe auch selbst ein wenig getestet, hatte aber nicht so viel Zeit. Schaue bitte, ob es bei Dir läuft. Wenn ja, bitte schließen, wenn nicht, bitte melden.  

Gruß
Pav

**Comment by tjeh** [comment]
Hallo Pav,

über den neuen Button wird der Parameter "Lenghten an EPG-record" nicht berücksichtigt.

Gruß
tjeh

**Comment by tjeh** [comment]
Hi Pav, 

zwar wird jetzt "Lenghten an EPG-record" berücksichtigt, aber dafür stimmen die EPG Zeiten rein gar nicht mehr.
Beispiel EPG gibt 20:15 bis 21:15 an... im Record Dialog erscheint 22:13 bis 23:17 ? Auch über die Zeitzonenoption in der Config konnte ich das Problem nicht beheben?

Gruß
tjeh

**Comment by Pavion** [comment]
Irgendwie kann ich es nicht nachvollziehen. Wann siehst Du diesen Unterschied? Ist es in Tabellen- und in Chart-Form so? Wird die angelegte Aufnahme auch falsch programmiert? Ist die Zeit von EPG wirklich korrekt?

**Comment by tjeh** [comment]
EPG komplett reset und neu geladen. Hier mal 2 Bilder was ich meine (vor dem Fix hat alles ohne Probleme funktioniert):

![1](https://cloud.githubusercontent.com/assets/4035535/9967465/04468cd2-5e43-11e5-987d-74f9fe9fb788.PNG)
![2](https://cloud.githubusercontent.com/assets/4035535/9967468/065b9260-5e43-11e5-8b33-ece820bb02ed.PNG)

**Comment by Pavion** [comment]
Hallo Tjeh, 

ich konnte Dein Problem zwar immer noch nicht nachvollziehen, habe aber einfach eine andere Herangehensweise probiert. Schaue bitte, ob es so besser klappt. 

Gruß
Pav

**Comment by tjeh** [comment]
Hi Pav,

dein neuer Ansatz funktioniert. EPG Zeiten werden nun korrekt übernommen.

Gruß
tjeh
