### ISSUE TITLE
Proxy can't be disabled

### ISSUE THREAD

**Issue by Pavion** [Pavion/tvstreamrecord#15]

**Comment by tjeh** [comment]
Um den Proxy zu deaktivieren muss die entsprechende Umgebungsvariable gelöscht werden - sprich nicht mehr vorhanden sein.

**Comment by Pavion** [comment]
Schon klar. Ich darf es halt nur nicht vergessen ^^

Am 3. September 2015 um 08:53 schrieb tjeh <notifications@github.com>:
