### ISSUE TITLE
Erweiterungsvorschläge für tvstreamrecord

### ISSUE THREAD

**Issue by tjeh** [Pavion/tvstreamrecord#16]
Hallo Pav,

nach weiterem rumspielen mit http (hls) streams (und Speicherung als mp4) sind mir folgende Punkte/Erweiterungsmöglichkeiten aufgefallen:

**Erweiterter ffmpeg support**
- loglevel von ffmpeg auswählbar, um ffmpeg fehler bei stream records zu finden (sprich warum kam es zu einem "retry"). Evtl. lässt sich ja der ffmpeg log umleiten?
- Möglichkeit Parameter an ffmpeg zu übergeben vor "-i", also "Additional pre-input arguments". Hierdurch kann zb. die FrameRate und/oder ein custom header übergeben werden.
  _ffmpeg.exe -re -headers 'X-Forwarded-For: x.x.x.x' -i http://xxx/master.m3u8 ..._
- Möglichkeit Aufnahmen aus "retries" zusammenzuführen... es passiert zb. dass ein Stream kurzzeitig unterbrochen wird, und für eine Aufnahme mehrere "Teil-Aufnahmen" entstehen
- Meta Tags für recordings automatisch schreiben (zb. Titel)
- ggf. "-c copy -bsf:a aac_adtstoasc" als default für Additional output arguments?

**UI**
- Nach "submit changes" wird auf den General Tab gewechselt, egal auf welchem Untertab man war
- Edit Record Dialog (über Zahnrad) hat "create recording" als Titel?

**Advanced**
- Record name/path mask wird "default" aus Config übernommen, kann aber im jeweiligen Record Dialog noch angepasst werden - sprich sendungsspezifische Record name/path mask (und evtl. meta Tags)

Gruß
tjeh

**Comment by Pavion** [comment]
Hallo Tjeh,
und danke Dir für die Mühe, mir der Du mein Programm auseinander nimmst :) 
Nun der Reihe nach: 

1. Loglevel ist bereits auswählbar und wird auch umgeleitet. Die Eingabe erfolgt unter Konfiguration -> FFMPEG -> Zusätliche Parameter, zum Beispiel: 
<b>-acodec copy -vcodec copy -loglevel info</b>
Damit werden die Ausgaben im Programmlog angezeigt. 

2. Wäre möglich... ich kann mir aber nicht vorstellen, wem und warum es nützen würde. Jedenfalls hatte ich bisher keine Probleme gehabt, die damit zu beheben wären. Bist Du da anderer Meinung?

3. Ja, das wäre mit großem Aufwand möglich. Ich müsste alle aufgenommenen Dateien merken, im Anschluß ffmpeg erneut aufrufen, um sie zusammenzufügen, Endergebnisse irgendwie kontrollieren und die Quelldateien löschen. Hier steckt auch ein riesiger Fehlerpotential. Was ist, wenn das Ergebnis doch nicht lesbar ist? Was ist, wenn ffmpeg die Dateien doch nicht zusammenfügen kann? Usw., usw. Ich biete ja auch nur eine Oberfläche für ffmpeg an und kann nicht den gesamten Funktionsumfang dieses doch umfangreichen Programms für alle Streams und Geräte unterstützen. Unterm Strich soll es in einer stabilen Umgebung auch keine Unterbrechungen geben. Aus Neugier jedoch: https://trac.ffmpeg.org/wiki/Concatenate 

4. Nun lasse ich mit ec9cd387c0800160c7b82e5db59e0a5adb1bea24 die Befehlszeile von ffmpeg parsen, um auch dort nach gleichen Platzhaltern zu suchen. Das könnte dann so aussehen:
<b>-acodec copy -vcodec copy -loglevel info -metadata title="%title%"</b>
Aber auch hier habe ich das gleiche Problem mit der Unterstützung. So wird es wohl je nach ffmpeg-Version und Streamtyp unterschiedlich behandelt -- in meinem Fall sehe ich bei folgender Befehlszeile: 
<b>ffmpeg -i http://meinStream -t 10 -acodec copy -vcodec copy -metadata title="Mein Supertitel" test.ts</b>
meinen Titel im VLC nur hier:
![meta](https://cloud.githubusercontent.com/assets/1370084/9880199/ec3fb48a-5bca-11e5-8d3a-388a7ec12afc.png)
Ich lasse die Funktionalität halt so drin, falls Du was probieren willst. Wie dem auch sei, einem typischen Nutzer wären die Zusammenhänge kaum zu erklären. 

5. Ganz ehrlich: nicht mal bin mir sicher, was das genau bedeutet. Menschen haben nun mal ganz unterschiedliche Stream-Quellen und auch nicht jede DS kommt mit einer zusätzlichen Umkodierungslast in Echtzeit aus. Man kann es so einstellen und, wenn man möchte, soll man es auch ruhig tun. -acodec copy ist aus meiner Sicht die ressourcengünsigste Lösung.

6. Stimmt. Ein Überbleibsel einer alten POST-Implementierung. Geändert in 96acf8e7fce55dcee68740f685a5ceca9bde4ab6

7. Stimmt. 799874825f03c408a1a057949b81161535af682b

8. Prinzipiell logisch, habe ich mir auch schon überlegt. Einerseits glaube ich nicht, dass der Bedarf groß ist, andererseits vermüllt es irgendwie für die meisten Nutzer das Interface. Ich behalte es dennoch als Erinnerung: #17.

Gruß
Pav

**Comment by tjeh** [comment]
Hallo Pav,

immer gerne :)

1. die Parameter parst du ja in (https://github.com/Pavion/tvstreamrecord/blob/master/tvstreamrecord.py#L980). Somit überschreibt man mit FFMPEG -> zusätzliche Parameter den loglevel. Ich hatte hier eher daran gedacht, dass es eine dropdown Auswahl in der Config sein könnte. --> Daher wohl "nur" nice to have

2. ziemlich wichtig :) Aktuell nutze ich den Proxy support, um einen Header zu übermitteln. Sofern man Parameter vor "-i" an FFmpeg übergeben könnte, wäre der Proxy Support nicht weiter notwendig. *ffmpeg.exe -re -headers 'X-Forwarded-For: x.x.x.x' -i http://xxx/master.m3u8* ist hier ein typisches Beispiel wie ich derzeit TV aufnehme.

3. vielleicht ist eine Zwischenlösung, dass am Ende der Aufnahme eine Logdatei erstellt wird, in der alle Retries inkl Dateinamen (für diese Aufnahme) genannt werden. Dann könnte ich mal mit [Concatenate](https://trac.ffmpeg.org/wiki/Concatenate) bzw. [MP4Box](https://gpac.wp.mines-telecom.fr/mp4box/) rumspielen :)

4. Perfekt, funktioniert wunderbar. Die verfügbaren und umgesetzten metadaten hängen vom Containerformat ab. Da ich wegen meinem Samsung in mp4 aufnehme (bei ts Aufnahmen ist ein Vor/Zurückspulen nicht möglich) funktioniert zb. der Tag title so wie vorgesehen (sprich taucht in VLC im Tab Allgemein auf.)

5. Nur ein Hinweis im zusammenhang mit mp4 container. Diese parameter stellen sicher, dass ein vernüftiges mp4 file am ende der Aufnahme durch ffmpeg entsteht. Ja die DS hatte ich jetzt nicht mehr so auf dem Schirm, da ich tvstreamrecord auf einem NUC betreibe (somit kann sich ffmpeg auch austoben).

6. funktioniert
7. funktioniert

8. Zumindest ein nice to have :)

9. Warum gibst du die Möglichkeit pro Channel eine eigene Dateierweiterung zuzuweisen, aber im Umkehrschluss gibt es nicht die Möglichkeit eigene FFmpeg parameter pro channel zuzuweisen?

Gruß
tjeh

**Comment by Pavion** [comment]
Hi!

Jetzt bin ich wieder dran: 

Zum Thema Loglevel. Dadurch, dass die zusätzlichen Parameter ganz am Ende stehen, haben sie automatisch eine höhere Priorität, als die Zuvorstehenden. Solltest Du also "-loglevel info" in diesem Feld angeben, so dass es am Ende so aussieht: "-loglevel error -loglevel info", zählt immer "info". Also ist es prinzipiell möglich, loglevel zu ändern, eine separate ComboBox sehe ich daher nicht als erforderlich. 

ffmpeg ist schon ein komisches Thema. Eigentlich nicht geplant, bin ich inzwischen nur zu einem ffmpeg-GUI geworden. Davon gibt es aber auch schon viel zu viele>. Eigentlich sollte ich die Hälfte weg schmeißen, das Tool in ffmpeg-GUI umbenennen und dann alles darauf umstellen, nur fehlt mir die Zeit und Geschick dafür. Es gibt auch einige Bedenken, die ich lieber per Mail diskutieren würde. Wie gesagt, schweres Thema.

MfG
Pav

**Comment by tjeh** [comment]
Hi, 

können wir gern auch per Mail diskutieren, falls du dazu lust hast :)

(tvstreamrecord@gmail.com ?)

Gruß
tjeh

**Comment by Pavion** [comment]
ja

**Comment by sl060270** [comment]
Nach nun einigen Wochen Nutzung wäre es aus meiner Sicht das "Killerfeature", mehrere Aufnahmen aus der EPG-Liste mit einem "Knopfdruck" erstellen zu können. Die Lieblingsserie, die ich regelmäßig aufnehme, kommt nicht zu regelmäßigen, sondern stets zu unterschiedlichen Zeiten. Dementsprechend ist die sich wiederholende Aufnahme hier keine Option. Vorstellen würde ich mir das so, dass per Suchwort die 15 Einträge/Sendungen kommen, diese dann markiert werden können und mit separatem Knopf gesammelt zur Aufnahmeplanung "rübergereicht" werden. Momentan verhält sich ja das Programm so, dass nach einer Aufnahme in das Aufnahmemenü gesprungen wird und dann das ganze wieder von vorne angefangen werden muss. Mühsam.... :-(

**Comment by Pavion** [comment]
Hallo und willkommen bei meinem kleinen Tool. 

Eine Funktion zur _automatischen_ Aufnahme nach Schlüsselwort gibt es derzeit tatsächlich nicht, auch wenn sie schon häufiger angefragt wurde. Die Gründe dafür sind:
- die EPG-Daten sind nicht immer vorhanden;
- die EPG-Daten reflektieren nicht zwangsläufig den aktuellsten Stand, da sie meist einige Zeit im Voraus generiert wurden; 
- ein zu breit gefächertes Schlüsselwort könnte plötzlich in einer anderen Sendung vorkommen und eine wichtige Aufnahme gefährden.

Es gibt jedoch ein Workaround: wenn Du bei der Erstellung einer Aufnahme aus EPG nicht auf "Aufnehmen" drückst, sondern auf "Bearbeiten und Aufnehmen", wirst Du danach nicht zu den Aufnahmen weitergeleitet, sondern bleibst in der Tabelle mit weiterhin aktivem Filter. 

Ein "Alle aufnehmen" Knopf in der EPG-Listenansicht ist eine interessante Idee und könnte theoretisch schon implementiert werden, eine Fehlbedienung könnte hier jedoch mehrere Tausende Aufnahmen verursachen, die nicht leicht zu beräumen wären und gewisse Performance-Probleme mit sich ziehen würden. 

Gruß
Pav

**Comment by Pavion** [comment]
https://github.com/Pavion/tvstreamrecord/releases/tag/1.4.0

Da die Listenansicht jetzt nicht mehr weiterleitet und Löschen möglich ist, können nun mehrere gefilterte Sendungen schnell aufgenommen werden.
