### ISSUE TITLE
Doesn't reload xmltv-data after cleanup

### ISSUE THREAD

**Issue by migmedia** [Pavion/tvstreamrecord#20]
After using `Delete/reset all EPG data` the xmltv-data isn't reloaded. Mentioned in the log: `XMLTV: no new data / unknown error, try again later`, but the files `epglist` stays empty.

The `Delete/reset all EPG data`-action should reset the import-timestamps / change-detection, too. To force a clean reload of the epg-data.

**Comment by migmedia** [comment]
strange, it should work as expected. 

tvstreamrecord.py:616
```python
@post('/removeepg')
def removeepg():
    sqlRun("DELETE FROM guide")
    sqlRun("DELETE FROM guide_chan")
    print ("All EPG data was deleted")
    return "null"
```
Maybe it's a problem on my synology .

**Comment by Pavion** [comment]
Hi there!

It's not quite an unexpected behaviour. According to [XMLTV guidelines](http://www.oztivo.net/twiki/bin/view/TVGuide/StaticXMLGuideAPI) all requests have to be provided with last request time, thus allowing a XMLTV server to deny incoming connections for reducing their traffic. This denial will cause an exception even if all EPG data was deleted. It would function again, once new data is available on server. 

To avoid this behaviour, additional table **caching** has to be purged too. See db917e00ff0ae1cb50d316d3bc13fe2a2ca252e0 for more details. 

If you need a new Synology version, please contact me again. If your question is answered, please close this issue. 

Best regards
Pav
