### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by jandahmen** [Pavion/tvstreamrecord#21]
NPO3_NL.ts could not be created. Please check your settings. Description: ('http error', 401, 'Unauthorized', )  pls assist

**Comment by Pavion** [comment]
Please provide some more infomation about streams you want to record. As it seems, you're trying to record a http://-based stream you have no access to (unauthorized). Make sure your streams are playable with any standart media player such as VLC.

**Comment by jandahmen** [comment]
i wanted to download a program on dutch television: 
NPO3 NL	NPO3 NL	01/28/2017 21:34	01/28/2017 22:15	Sa
#EXTM3U
#EXTINF:0,NPO3 NL
http://newlook.ddns.net:9880/live/amy1_94940/45028/2745.ts

and received the errormessage:
NPO3_NL.ts could not be created. Please check your settings. Description: ('http error', 401, 'Unauthorized', )

**Comment by Pavion** [comment]
With the link you've provided I'm receiving a small movie, which says "Sei stato bannato!", which is Italian for "that's forbidden". From server located in France(?). Can you really play the link you've provided with a media player? Or is it required to be authentificated?

**Comment by jandahmen** [comment]
every download has the same result (italian movie). I don't know what is going on. i am new with this program and i wanted to try it. i think i can better stop, for it gives me not what i want(download tv-programs). thanks for the help. regards  jan dahmen

**Comment by Pavion** [comment]
Sorry for having disappointed you. With the information you've provided I unfortunately couldn't help you. Maybe you've tried a wrong tool for your purpose after all. Still I thank you for your interest and your feedback and wish you good luck!
