### ISSUE TITLE
Zeitgleiche Aufnahmen

### ISSUE THREAD

**Issue by Mephiztopheles** [Pavion/tvstreamrecord#22]
Heyho,
mir ist aufgefallen, dass ich nicht 2 Sendungen zur gleichen Zeit aufnehmen kann.
Meine Fritbox bietet 4 Kanäle, theoretisch kann ich also 4 Sendungen gleichzeitig aufzeichnen.
Nun bin ich mir nicht sicher, ob man mit ffmpeg mehrere Streams zur selben Zeit öffnen kann, aber das wäre ein super Feature

**Comment by Pavion** [comment]
Hallo. 
An sich hat mein Tool keine solche Begrenzung, auch kann ich bei mir ffmpeg zwei Mal parallel laufen lassen. Was funktioniert also bei Dir nicht? Die erste Aufnahme oder die Zweite? Was steht dabei im Log und welche Dateien werden generiert? Mit dem ffmpeg-Parameter **-loglevel error** wird dort auch mehr Info mitgeschrieben. Vielleicht will/kann Deine Fritz nur einen Sender pro Endgerät liefern? Bitte etwas mehr Info, dann schaue ich gern nach. 
Gruß
Pav

**Comment by Mephiztopheles** [comment]
Hi, 
Die Aufnahmen wechseln sich immer ab
Erst der erste Kanal, der dann der zweite, dann wieder der erste und so weiter
In den log hab ich jetzt nicht geschaut, er sagt, dass bei dem stream etwas fehlgeschlagen ist und will es erneut versuchen (n/99)

**Comment by Mephiztopheles** [comment]
M3U upload parsing started
sind die letzten Meldungen

**Comment by Mephiztopheles** [comment]
```
FFMPEG record 'Test' ended with an error:
b'[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n    Last message repeated 1 times\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 1 times\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n    Last message repeated 1 times\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 1 times\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n    Last message repeated 1 times\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 1 times\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n    Last message repeated 1 times\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 1 times\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n    Last message repeated 1 times\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 2 times\r\n[mpeg2video @ 007f26e0] Invalid frame dimensions 0x0.\r\n[mp3 @ 007f17e0] Header missing\r\n    Last message repeated 61 times\r\nrtsp://192.168.178.1:554/?freq=426&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,103,1011,1012,1013,1014: Unknown error\r\n'
Something went wrong with 'Test', retry 1/99 in 10 seconds
```

**Comment by Pavion** [comment]
Es sieht für mich schon eher so aus, als würde Fritz die erste Verbindung kappen, bevor die Zweite aufgebaut wird. Und beim Versuch die Erste neu zu verbinden, wird wieder die Zweite gekappt. 
Wäre es möglich mit deinem Gerät auf dem PC zwei unterschiedliche Streams mit verschiedenen Media-Playern abzuspielen?

**Comment by Mephiztopheles** [comment]
Habs vom Laptop versucht - scheint nicht so
Was kann ich da machen? 
Hab ich was in der fritzbox vergessen?

**Comment by Pavion** [comment]
Kann ich so auf Anhieb gar nicht sagen, mein eigenes Gerät ist inzwischen extrem veraltet :) 
Welches Modell hast Du, vielleicht findet man was im Netz..?

**Comment by Mephiztopheles** [comment]
Fritzbox 6490 Cable

**Comment by Mephiztopheles** [comment]
Im Netz hab' ich dazu noch nichts gefunden...

Ist an der Liste denn was falsch? .. so pauschal...

ID | Sendername | Senderadresse
--------|----------|---------
1 | Disney Channel (DE) | rtsp://192.168.178.1:554/?freq=426&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,103,1011,1012,1013,1014		
2 | Comedy Central (DE) | rtsp://192.168.178.1:554/?freq=466&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,116,2941,2942,2944		
3 | DMAX | rtsp://192.168.178.1:554/?freq=466&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,115,2291,2292,2294		
4 | kabel eins | rtsp://192.168.178.1:554/?freq=442&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,109,2301,2302,2304,2306		
5 | Nickelodeon (DE) | rtsp://192.168.178.1:554/?freq=466&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,104,441,442,443,444		
6 | ProSieben MAXX | rtsp://192.168.178.1:554/?freq=626&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,104,6431,6432,6433,6434,6436		
7 | ProSieben | rtsp://192.168.178.1:554/?freq=442&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,101,2201,2202,2203,2204,2206		
8 | RTL II | rtsp://192.168.178.1:554/?freq=394&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,112,1601,1600,1602,1604,1606		
9 | RTL NITRO | rtsp://192.168.178.1:554/?freq=402&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,105,981,980,982,984,986		
10 | RTL | rtsp://192.168.178.1:554/?freq=122&bw=8&msys=dvbc&mtype=64qam&sr=6900&specinv=1&pids=0,16,17,18,20,101,6260,1401,1402,1403,1404,1406,6261		
11 | SAT.1 | rtsp://192.168.178.1:554/?freq=122&bw=8&msys=dvbc&mtype=64qam&sr=6900&specinv=1&pids=0,16,17,18,20,102,2701,2702,2703,2704,2706		
12 | SUPER RTL | rtsp://192.168.178.1:554/?freq=394&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,111,1501,1500,1502,1504,1506		
13 | VOX (DE) | rtsp://192.168.178.1:554/?freq=394&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,113,1701,1700,1702,1704,1706

**Comment by Pavion** [comment]
Ehrlich gesagt, kann ich das Problem nicht nachvollziehen :(
Mein Tool hat, wie gesagt, keine Begrenzungen diesbezüglich, ffmpeg läuft prinzipiell auch parallel. Ich vermute immer noch, dass die Übertragung von der Fritz unterbrochen wird. Ein indirekter Hinweis darauf findet sich auf ihrer `[Produktseite](https://avm.de/service/fritzbox/fritzbox-6490-cable/wissensdatenbank/publication/show/1528_Fernsehempfang-in-FRITZ-Box-einrichten/)`: 

> Maximal vier unterschiedliche TV-Programme können gleichzeitig auf **verschiedenen** Netzwerkgeräten wiedergegeben werden.

Ich würde dann auch vermuten, wenn Du zwei mal einen **gleichen** Stream aufnimmst, könnte es daher sogar klappen, was auch ffmpeg entschuldigen würde. 

Ich wünschte, ich könnte mehr helfen, auf Anhieb fällt mir jedoch nichts mehr ein. Wenn Du einen Terminalzugang zu Deiner DS freigeschaltet hast, kannst Du in zwei verschiedenen Sitzungen Deinen Stream per Hand aufzunehmen versuchen, vielleicht siehst Du da mehr.

**Comment by Mephiztopheles** [comment]
DS?

**Comment by Pavion** [comment]
Ich nahm an, dass Du die Synology-Version verwendest (DS = Disk Station)....

**Comment by Mephiztopheles** [comment]
Synology-Version von was ? :D
ich hab jetzt gerade auch mal getestet, ich hab eine Aufnahme laufen und hab versucht dabei auf dem gleichen Geräte, den gleichen Kanal aber über `http://localhost:8030/live/6.m3u` anzusehen ... klappt auch nicht, also hier werden auch die streams gegenseitig unterbrochen

**Comment by Mephiztopheles** [comment]
aaaah... wie mach ich das? :D

**Comment by Pavion** [comment]
Nutzest Du denn mein Tool auf einem NAS oder einem anderen Gerät? Jetzt bin ich auch verwirrt ^^

Wie es jedenfalls aussieht, kann ich Dir hier leider nicht wirklich weiter helfen, vor allem, wo ich das selbst gar nicht erst nachvollziehen kann :(

**Comment by Mephiztopheles** [comment]
hab' hier meinen Standrechner mit Python versorgt und einen Task unter Windows eingerichtet, welcher den Server startet

**Comment by Pavion** [comment]
....auf welchem Gerät auch immer, kannst Du jedenfalls ffmpeg auch direkt (und/oder mehrfach) starten:
`
ffmpeg -i 'rtsp://192.168.178.1:554/?freq=442&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,101,2201,2202,2203,2204,2206' -y -t 60 -loglevel error -acodec copy -vcodec copy '/volume1/pfad_zu_Deiner_Datei'`

**Comment by Mephiztopheles** [comment]
apropos... Server im HIntergrund also ohne Konsole? möglich? :D

**Comment by Pavion** [comment]
Ach so, auch schön :) Die meisten Nutzer verwenden eine spezifische Version, die für NAS-Server der Fa. Synology kompiliert wird. Also zu Deiner letzten Frage: ja, einen Server im Hintergrund ohne Konsole ist oft ein NAS.

**Comment by Pavion** [comment]
Der übernimmt dann die Aufgaben Dateien zu bunkern, Sendungen aufzunehmen, Überwachungskameras zu überwachen, Mail-/Web-Services beizustellen usw.

**Comment by Mephiztopheles** [comment]
Ich kenne NAS nur als Datei-Server

**Comment by Pavion** [comment]
Das ist nun von gestern. Die modernen NAS bieten inzwischen (auf einer vollständigen Intel-Plattform) ein vollständiges Linux-Betriebssystem mit grafischer Oberfläche.

**Comment by Pavion** [comment]
Schau mal [hier](https://www.synology.com/de-de/dsm/6.1/features) (**kein** Werbelink!)

**Comment by Mephiztopheles** [comment]
Willst du eventuell über mail weitermachen?`^^
hab' mal ffmpeg ausprobiert und bekomme `'rtsp://192.168.178.1:554/?freq=442: Invalid argument` in rot

**Comment by Pavion** [comment]
Wie Du meinst, Du hast mich ja hier angeschrieben, obwohl ich auch meine E-Mail angebe :) 

Hast Du vielleicht die '' um Deine URL vergessen?

**Comment by OlafWinkler** [comment]
Hallo,
@Pavion: Tolles Tool für die DS, vielen Dank!
Bei meiner Fritzbox 6590 hatte ich auch das Problem, dass ein neuer Aufnahmestream einen laufenden abbrach. Ich hatte die Kanalliste aus der FB exportiert. Dort war bei jedem Kanal ein "avm=1&" in der rtsp-URL, was wohl den Tuner der FB festlegt. Ich habe also die Kanalliste exportiert, überall "avm=1&" gelöscht (Suchen/Ersetzen gegen nichts) und dann wieder importiert. Nun kann ich parallele Aufnahmen mit meiner FB machen. Zumindest mit zweien habe ich es bereits probiert.
Vielleicht hilft's ja jemandem.
Viel Spaß
Olaf
