### ISSUE TITLE
EPG Chart - mach ich was falsch?

### ISSUE THREAD

**Issue by Mephiztopheles** [Pavion/tvstreamrecord#23]
Option | Wert
------------ | -------------
EPG Aufnahme verlängern um (vor und nach) [Minuten] | 3
XMLTV-Import einschalten | an
Suchpfad für XMLTV-Import | http://xmltv.spaetfruehstuecken.org/xmltv/datalist.xml.gz
Zeitverschiebung für die XMLTV-Daten (in Stunden) | 0
mc2xml komplette Befehlszeile (nur x86 CPUs, Vorgabe: leer) * |
Import aus Streams einschalten ** | aus
Maximale Importdauer pro Sender [Sekunden] (Vorgabe '60') ** | 60
Uhrzeit für täglichen automatischen Import (hh:mm Format, 24h-basiert, Vorgabe '0' zum Ausschalten) | 16:00
EPG-Listenmodus. Ausschalten für die Client-seitige Verarbeitung (mehr Netzwerklast), einschalten für die Server-seitige Verarbeitung (mehr Serverauslastung) | an
Nur Client-seitig: maximale Anzahl von Programmen, die vom Server angefragt werden (frühere zuerst), hilft beim langsamen Seitenaufbau | 5000

Das sind die Einstellungen für EPG

Als Meldungen in der Konsole bekomme ich folgendes
`EPG grabbing started on Disney Channel for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on COMEDY CENTRAL/VIVA for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on DMAX for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on kabel eins for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on Nickelodeon for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on ProSieben MAXX for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on ProSieben for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on RTL II for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on RTL NITRO for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on RTL for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on SAT.1 for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on SUPER RTL for 60 seconds
Supplied stream could not be found or opened, aborting...
EPG grabbing started on VOX for 60 seconds
Supplied stream could not be found or opened, aborting...
tvstreamrecord v.1.3.0 / XMLTV import started
XMLTV: reading URL http://xmltv.spaetfruehstuecken.org/xmltv/datalist.xml.gz with 144820 bytes
XMLTV import completed with 0 entries`

**Comment by Pavion** [comment]
Import aus Streams funktioniert seit langem leider nur bei ganz spezifischen Streams. Als kostenlose Alternative ist der Import über XML-Daten möglich. Dabei ist es wichtig, dass Deine Sender genau so benannt sind, wie der XML-Anbieter sie benennt. Für die voreingetragene Quelle findest Du [hier](http://xmltv.spaetfruehstuecken.org/xmltv/channels.html) die Liste der unterstützten Sender und ihre Namen (vorwiegend ÖffRechtliche). Alternativ kannst Du die hier probieren:
`http://xmltv.xmltv.se/datalist.xml.gz`. Die hat sogar "ProSieben MAXX" und sollte sofort klappen.

**Comment by Mephiztopheles** [comment]
Werde ich morgen ausprobieren

**Comment by Mephiztopheles** [comment]
Ja, klappt recht gut.
Nur finde ich es nicht so schön, dass ich viele Sender mit (DE) beenden muss :/

und ich bekomme diesen log:
```
XMLTV: no new data / unknown error, try again later (http://xmltv.xmltv.se/prosieben.de_2017-06-16.xml.gz)
XMLTV Warning: connection timeout detected, retry in 5 seconds
````

Am ende steht auch immer `XMLTV import completed with 0 entries`, was aber anscheinend nicht stimmt

**Comment by Pavion** [comment]
XMLTV ist schon eine einfache schöne open source Sache. Manchmal kann es dabei nun aber auch zu Fehlern beim Einlesen oder Übertragung kommen. Aktuell klappt es bei mir mit der von Dir angegebenen Datei. Wenn es nur temporär ist oder auf eine bestimmte Datei begrenzt ist, ist es eher unbedenklich. Wenn es systematisch sein sollte, melde Dich bitte erneut. 
Übrigens, eine interessante Alternative ist die Verwendung vom kostenfreien Tool [TVBrowser](http://www.tvbrowser.org/), welches dann mein Programm über ein Plugin "beauftragt".

**Comment by unfassbarstephan** [comment]
Ich möchte das Thema noch einmal kurz aufgreifen. Habe die EPG von "http://xmltv.xmltv.se/datalist.xml.gz" eingebunden und ebenfalls gleich in der Senderliste benannt. Alle gespeicherten Sender funktionieren, außer "vox.de", der befindet sich leer am Ende der Chart. Was könnte da das Problem sein?

**Comment by Pavion** [comment]
stelle bitte sicher, dass Dein sender auch wirklich `VOX (DE)` heißt

**Comment by unfassbarstephan** [comment]
Danke für die super schnelle Rückmeldung, das Leerzeichen war es. Da ich die EPG bereits vor einer Weile implementiert hatte, wo kann man gleich noch einmal die Klarnamen der Sender auslesen? In der jeweiligen Sender-XML hatte ich den nämlich nicht gefunden.

**Comment by Pavion** [comment]
doch :) hab Deinen Link im Browser geöffnet, nach VOX gesucht - Tada! :)

Am So., 10. Feb. 2019, 20:13 hat unfassbarstephan <notifications@github.com>
geschrieben:
