### ISSUE TITLE
M3U Playlist from URL?

### ISSUE THREAD

**Issue by DiGiTaLAnGeL92** [Pavion/tvstreamrecord#24]
Hi Pavion, i would like to ask you if you can add URL support instead of manual uploading of an M3U playlist. And maybe even autoupdate it everyday automatically. It would be very cool! Thanks!

**Comment by Pavion** [comment]
Hi Angel. What is your setup, so you would need to refresh your channel list daily? With channel names changed or re-sorted, records may become broken. With channel URLs changing, you would be losing your record anyway.

**Comment by DiGiTaLAnGeL92** [comment]
Actually i'm getting a list containing channels as .ts streams... the provider updates it often with new channels, while the pre-existing one keeps the same URL even after updates... it would be nice to have this list automatically updated with new channels... i dont know how the records are stored, but if it's based on the url of the stream there should be no issues.

**Comment by Pavion** [comment]
Well... it can't possibly be _that_ frequent? You could then download the file and upload it in my tool, couldn't you? There is a switch "Append to existing channels", which makes sure your current channels (name, not url based) are kept.
