### ISSUE TITLE
Better EPG overlay

### ISSUE THREAD

**Issue by Pavion** [Pavion/tvstreamrecord#27]
https://www.synology-forum.de/showthread.html?37898-tvstreamrecord-Aufzeichnen-von-HTTP-Streams&p=786948&viewfull=1#post786948

Idee: 
1) bei Abgleich Aufnahme <-> EPG soll nicht mehr mit Deltas gerechnet werden, sondern verglichen, ob ein EPG-Eintrag *in* dieser Zeit ist. 
Es ist zu prüfen, ob es Auswirkungen auf die Listenansicht hat! 
Es ist zu prüfen, ob Sekundenwert passt (d.h. Aufnahme und EPG wird immer mit xx:xx:00 gespeichert o.Ä.), 
2) zusätzlicher Overlay (zu-/abschaltbar?) könnte generell einen Balken einer Aufnahme in der EPG-Ansicht mit anderer Farbe darstellen -- **unabhängig davon**, ob und welche EPG Einträge darunter sind. Notfalls müsste für die Sender, die keine EPG-Daten haben, bei der Datenrückgabe ein Dummy erstellt werden.

**Comment by thommy-76** [comment]
zusätzlich sollten beim Abgleich auch die bei der Aufnahme ggf. gesetzten Wiederholungen berücksichtigt werden, was bisher nicht geschieht :)
