### ISSUE TITLE
Mobile Aufnahmen ignorieren Verlängerung

### ISSUE THREAD

**Issue by 0xhaDe** [Pavion/tvstreamrecord#31]
Hallo,

wenn ich eine Aufnahme über die mobile Ansichtaufnehmen will und dazu einen EPG-Eintrag auswähle, ist in der folgenden Ansicht der Start- und Stopzeiten die Vor- bzw. Nachlaufzeit nicht berücksichtigt. Ich kann zwar die Zeit natürlich verändern, aber es wäre angenehmer, wenn als Standard die Verlängerung berücksichtigt wäre.

**Comment by Pavion** [comment]
https://github.com/Pavion/tvstreamrecord/releases/tag/1.4.0
