### ISSUE TITLE
delete all channel option 

### ISSUE THREAD

**Issue by darshanvithani** [Pavion/tvstreamrecord#36]
now we don't have delete all channel option and same for epg

**Comment by Pavion** [comment]
There is no "delete all channels" but you can overwrite them all by importing a new .m3u file. You can also delete everything by importing an empty playlist containing this line only:
`#EXTM3U`

There *is* a "delete all EPG" option, found all the way down in Config -> EPG
(`Delete/reset all EPG data`)

**Comment by darshanvithani** [comment]
perfect thanks : can i record direct without add m3u .. record with direct url

**Comment by Pavion** [comment]
No it's not possible. TSR is not a download manager, it's rather a VCR for fixed channels (urls).
