### ISSUE TITLE
Zeitzone im EPG

### ISSUE THREAD

**Issue by 0xhaDe** [Pavion/tvstreamrecord#38]
Hallo,

nach der Umstellung bei XMLTV vor ein paar Wochen sind die Uhrzeiten in den XML-Dateien nicht mehr in Lokalzeit, sondern in UTC.
Daher musste ich bei "Zeitverschiebung" in den EPG-Einstellungen eine Verschiebung von +2 Stunden einstellen. Jetzt mit der Zeitumstellung musste ich auf +1 Stunden zurückstellen. Dabei haben sich die Einträge nicht verändert, die Tagesschau kommt also um 21 Uhr statt um 20 Uhr.

Wäre es möglich die Zeitzone der NAS abzugreifen und eine automatische Verschiebung der EPG-Einträge von der UTC-Zone in die lokale Zone zu machen?
Und wäre es zudem möglich, bereits importierte EPG-Einträge beim Verändern der Zeitverschiebung mitzuverschieben?

MfG,
haDe

**Comment by Pavion** [comment]
Hi! Sorry, kam eine Weile lang nicht dazu zu antworten... 
Wie es aussieht, ist es jetzt die neue Vorgehensweise von xmltv.se, die Zeiten für die UTC+0 zu übermitteln, anstelle von lokaler Zeit des Senders. 
Nun könnte ich mir einen Schalter vorstellen:
- on (default bei Installation): bei Bedarf lokale Zeit verwenden (Offset ausgegraut)
- off (default beim Upgrade, um Kompatibilität zu wahren): wie jetzt festen Offset eingeben und verwenden (default 0h). 
Im ersten Fall würde dann automatisch versucht, aus `20:00 (UTC+0)` z.B. `21:00 (UTC+1) zu basteln. 

Allerdings gäbe da eine kleine Unsauberkeit: wenn es einen anderen Anbieter/Quelle gibt, der **kein** UTC-Offset übermittelt, was mache ich dann? Soll ich dann annehmen, dass die Zeiten lokal, in UTC+0 oder in z.B. PST sind? Ich würde ersteres meinen. Notfalls müsste man dann doch per Hand nachregeln... 

Was hältst Du davon? 

Gruß
Pav

**Comment by Pavion** [comment]
P.S. Ja, Du hast auch Recht, nachträgliche Offset-Änderung verändert absichtlich nicht die bestehenden Einträge. Auch ist es d.Z. nicht möglich, beim Abruf der Daten im Zeitraum der Zeitumstellung mit zwei verschiedenen Offsets zu arbeiten. Die einzige aktuell mögliche "schmutzige" Lösung ist es, am jew. Sonntag nach der Zeitumstellung alle EPG-Daten zu löschen und mit dem neuen Offset einzulesen, was natürlich irgendwie doof ist.

**Comment by 0xhaDe** [comment]
Hi,
ich hab jetzt leider auch ne Weile gebraucht.
Das mit dem Schalter sehe ich auch so, den Fall, dass jemand den Offset bei angeschalteter Option braucht gibt es wohl nicht.

Und wenn ein Anbieter kein Offset in den XML-Dateien mitliefert würde ich einfach die lokale Systemzeit nehmen. Kannst ja nicht wissen was der genau liefert. Auch wenn das dann vermutlich die Lokalzeit des Senders ist, aber da kann man dann ja nachregeln.

MfG,

haDe

**Comment by Pavion** [comment]
Hi @0xhaDe!

Das Handling von Zeitzonen ist in Python generell eine sehr schmerzhafte Geschichte, was die erste Suche bei Google offenbart. Um die Kompatibilität zu Python 2.7 und 3 gleichzeitig beizubehalten und dabei systemunabhängig zu bleiben, müssten Dritt-Bibliotheken (z.B. **Pytz**) eingebunden und mit TSR ausgeliefert werden, diese haben wiederum weitere Bibliotheken als Abhängigkeiten... und so weiter. Am Ende habe ich mein Projekt verdreifacht, nur um das eine Problem zu lösen :( 

Falls Du irgendwelche Ideen oder vielleicht sogar fertige Ansätze hast, würde ich sie mir gern anschauen, ansonsten muss ich das Problem wohl erstmal etwas vertagen... immerhin habe ich bis zu 29. März 2020 Zeit 🤣 

Gruß
Pav
