### ISSUE TITLE
ffmpeg Problem

### ISSUE THREAD

**Issue by bahrb** [Pavion/tvstreamrecord#39]
Hi, erstmal vielen Dank für die Arbeit an dem Programm!

Auf meinem Synology DS112+ ist ffmepg 2.7.1 als ausgeliefertes Paket (/usr/bin/ffmpeg) enthalten, die Aufnahme scheitert dann leider mit:
`Unrecognized option 'rtsp_transport` anscheinend kennt diese Version das Flag noch nicht.

Daher habe ich zusätzlich ffmpeg über das Community-Paket(/volume1/@appstore/ffmpeg) installiert in Version 4.1. Da bekomme ich aber folgendes Problem `FFMPEG could not be started. Error: [Errno 13] Permission denied`

Nun habe ich schon diverse Rechteänderungen für das ffmpeg Verzeichnis ausprobiert aber keine führte zum Erfolg. Ich weiß nicht mit welchen Rechten der Python-Prozess läuft um ffmpeg aufrufen zu dürfen?

**Comment by Pavion** [comment]
Hi! Es gibt eigentlich keine spezielle User oder Rechte beim Aufruf von TSR oder ffmpeg...
Kannst Du denn dieses Tool selbst in der Konsole aufrufen? Welchen Pfad verwendest Du? 
Richtig, glaube ich, wäre:
`/volume1/@appstore/ffmpeg/ffmpeg`
Du kannst auch eine für deine CPU passende Version von ffmpeg direkt herunterladen, irgendwo in /volume1/downloads oder so ablegen und von dort aus aufrufen.

**Comment by bahrb** [comment]
Danke, das Problem hat sich gelöst, ich habe übersehen, dass es sich um den vollen Pfad inkl. binary handelt.
Mit `/volume1/@appstore/ffmpeg/bin/ffmpeg` hat es dann geklappt.
