### ISSUE TITLE
ffmpeg-Einstellungen

### ISSUE THREAD

**Issue by 0xhaDe** [Pavion/tvstreamrecord#40]
Hi,

mir ist letztens aufgefallen, dass bei einer meiner Aufnahmen die Tonspur mit Bildbeschreibungen für Blinde drin war.
Nach ein wenig Recherche habe ich festgestellt, dass ffmpeg normalerweise nur je eine Video-, Audiospur auswählt und zwar die Videospur mit der höchsten Auflösung, die Audiospur mit den meisten Kanälen. Das war bei dem von mir aufgenommenen Film halt die für Blinde.

Das kann ich natürlich bei mir fixen, aber ich dachte ich geb mal bescheid, dass das in der Standardinstalltionseinstellung für den Benutzer vielleicht nicht ersichtlich ist.

Folgendes würde laut ffpeg-wiki alle (Video- und Audio)Kanäle kopieren:
`ffmpeg -i input -map 0 -c copy output.mp4`

MfG,
haDe

**Comment by 0xhaDe** [comment]
#41

**Comment by Pavion** [comment]
danke!
