### ISSUE TITLE
add -ignore_unknown parameter for ffmpeg call

### ISSUE THREAD

**Issue by kaiomatico** [Pavion/tvstreamrecord#44]
Hi first of all thank you for the great project! However with my Fritz Box 6490 Cable tvsd.m3u I get an error on the console saying: 

Cannot map stream #0:4 - unsupported type.
If you want unsupported types ignored instead of failing, please use the -ignore_unknown option
If you want them copied, please use -copy_unknown

So I tested the -ignore_unknown parameter with manually launching ffmpeg like this:
ffmpeg -i "rtsp://192.168.0.1:554/?avm=1&freq=402&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,105,981,980,982,984,986,987,988" -map 0 -ignore_unknown -c copy test.ts

And everything is working fine playing back the test.ts file with VLC media player :) So I guess Fritz Box users need the -ignore_unknown parameter for their tvsd m3u stream playlist (at least for Vodafone)

**Comment by kaiomatico** [comment]
Oops I just saw that you already give the user the option to add additional arguments/parameters in the GUI using  config->ffmpeg support->additional arguments. But maybe you could add this information to the software manual so Fritz Box users can look up this information to add the argument

**Comment by Pavion** [comment]
Fixed sometime, see
https://github.com/Pavion/tvstreamrecord#ffmpeg-support
Thanks for suggestion though!
_doin' some clean-up :)_
