### ISSUE TITLE
tvstreamrecord DS 420+

### ISSUE THREAD

**Issue by Herodes1** [Pavion/tvstreamrecord#46]
Hallo Zusammen,

ich habe folgendes Problem und weiss nicht mehr weiter. Ich habe alles nach Installationsanleitung auf meiner neuen DS420+ installiert ( +tvstreamrecord Synology package documentation) aber es wird keine Aufnahme getätigt.

Folgende Fehlermeldung erhalte ich. 

['/volume1/@appstore/MediaServer/bin/ffmpeg', u'-i', 'rtsp://192.168.74.1:554/?avm=1&freq=306&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,101,102,104,170,176,2171', u'-y', u'-t', u'2138', u'-loglevel', u'fatal', u'-acodec', u'copy', u'-vcodec', u'copy', u'/volume1/video/20200709111121 - Test.ts']
--
2020-07-09 11:11:26.376 | FFMPEG record 'Test' ended
Something went wrong with 'Test', retry 93/99 in 10 seconds

Ich denke es hängt an FFMPEG. Den Pfad habe ich kontrolliert und der Stimmt. 

ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --enable-version3 --enable-nonfree --enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib --disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffserver --disable-ffplay --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100

TV Sender von der Fritzbox DVBc am Beispiel ARTE : 

rtsp://192.168.74.1:554/?avm=1&freq=306&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,400,401,402,403,407,408,404,470,1276,2171

/volume1/@appstore/MediaServer/bin/ffmpeg

**Comment by Pavion** [comment]
Hallo! Nimm lieber nicht die Version von MediaServer, sondern von
VideoStation oder installiere gleich die FFMPEG-Version der SynoCommunity,
die dann den Pfad hat:
/volume1/@appstore/ffmpeg/bin/ffmpeg
Wenn Du eine erweiterte Fehlerbeschreibung sehen möchtest, füge -loglevel
error der Befehlszeile hinzu.
Im Zweifelsfall versuche bitte den gesamten Befehl in der Konsole
auszuführen, meistens sieht man gleich, woran es liegt.

/volume1/@appstore/ffmpeg/bin/ffmpeg -i 'rtsp://
192.168.74.1:554/?avm=1&freq=306&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,100,101,102,104,170,176,2171'
-y -t 2138 -loglevel error -map 0 -acodec copy -vcodec copy
'/volume1/video/test.ts'

Gruß
Pav

**Comment by Herodes1** [comment]
Hallo Pax 

Die Änderung auf den Pfad /volume1/@appstore/VideoStation/bin/ffmpeg war die Lösung

DANKE


Mit freundlichen Grüßen 
Mario

**Comment by Pavion** [comment]
Freut mich 😄 
Danke für die Rückmeldung!
