### ISSUE TITLE
Synology hat DSM 7.0 gestartet

### ISSUE THREAD

**Issue by solluh** [Pavion/tvstreamrecord#47]
Liebe Community,
ich habe schon am Alpha-Test der neuen Synology-Software teilgenommen und bin auch eigentlich ganz optimistisch, aber ich vermisse so richtig schmerzlich mein geliebtes tvstreamrecord.
Wird es eine Version geben, die auch auf der Version 7 von Synologys DSM läuft?
Vielen Dank!
Solluh

**Comment by todrees1967** [comment]
Das würde mich auch interessieren, bzw. freuen, wenn die Lösung weiter läuft.

**Comment by Pavion** [comment]
💤 Habe ich was verpasst?  
Ich habe noch 6.2.3 und ahne nichts... 
Hat sich da was verändert, dass es nicht mehr läuft?

**Comment by solluh** [comment]
Offenbar. Ich nutze die beta von DSM 7.0 (rausgekommen Anfang Dezember) und war vorher auch alpha-Tester. Leider läuft tvstreamrecord nicht auf der neuen Version. Kann ich irgend etwas beisteuern?

**Comment by Pavion** [comment]
Hm, keine Ahnung, ehrlich gesagt, habe gerade kaum technische Info dazu gefunden, was nicht gehen sollte. TSR ist eigentlich eine simple Python-Anwendung, die überall laufen soll, auch im Docker z.B., sofern unter DSM7 erhältlich. 
Es ist sicherlich eine Kleinigkeit aber ich habe nur ein heißes System und will es noch nicht updaten.
Gibt es denn Anhaltspunkte? Wird es nicht installiert, nicht gestartet?

**Comment by solluh** [comment]
Beim.Update auf die alpha startete es zwar (Status "läuft"), aber ich konnte keine Verbindung über den Port 8030 herstellen: blanke Seite.
Nach Update auf die Betaversion habe ich deinstalliert und wollte wieder reinstallieren. Ergebnis: "Ungültiges Dateiformat. Bitte wenden Sie sich an den Entwickler", auch bei der manuellen Installation.
Python Module und Python 2 laufen.

**Comment by Pavion** [comment]
Oje... Synology hat das Rechte-Konzept überarbeitet: 
https://github.com/SynoCommunity/spksrc/issues/4170
Offensichtlich wird es eine neue Art der Rechtevergabe geben, das werde ich erst ab Stable Build selbst testen können. 
Als Alternative kann TSR bestimmt im Docker laufen (sollte easy sein oder ich muss mich reinlesen, wie man so eine Datei schreibt). Falls DSM7 noch Konsolenzugriff bietet (tut sie?), kann TSR auch direkt als Daemon gestartet werden. Naja, halt überall, wo's Python gibt :P

**Comment by solluh** [comment]
Ja wenn ich davon jetzt nich Ahnung hätte... 😅
Da muss ich eben auf eine stabile 7er warten - hilft ja nichts... Freue mich aber sehr über deine Nachrichten.

**Comment by Pavion** [comment]
Ich habe mich heute intensiv mit dem Thema Docker beschäftigt und habe tvstreamrecord dort eingerichtet. 

[Docker](https://www.docker.com/) ist eine virtuelle Umgebung, die auch auf Synology installierbar ist und viele Vorteile bietet. 

tvstreamrecord läuft in einem Linux (alpine) Container mit vorinstalliertem python, ffmpeg und weiteren erforderlichen Bibliotheken und ist damit sowohl sicher als auch portabel. 
https://hub.docker.com/repository/docker/pavion/tvstreamrecord

Die Installation und Einrichtung von Docker auf Synology normal über Paketzentrum, Anleitung zum Einrichten hier: 
https://github.com/Pavion/tvstreamrecord#using-docker-on-synology

Offene Fragen: 
- Container aktualisieren sich nicht automatisch, beim Versionswechsel muss deinstalliert werden, Konfiguration wird in diesem Fall nicht übernommen. Auslagerung der Konfiguration zum Zielordner überlegen?

@solluh Ich denke, das bleibt die einzige Lösung für DSM7, die eigentlich auch wirklich besser ist. Könntest du es vielleicht testen?

BR Pav

**Comment by solluh** [comment]
Hallo Pav,

ich bin schwer begeistert und auch sehr dankbar für dein Engagement!
Zur Zeit bin ich gerade bei meiner Familie und far far away from DSM und  habe leider noch immer keine stabil funktionierende Möglichkeit der https-Verbindung zu meiner 918+ installiert bekommen.
Aber ich konnte mich per VPN (über Fritzbox) draufschalten, die Installation vornehmen und **BANG!** - ES LÄUFT!

Klasse - nun muss ich nur noch wieder die Kanäle aus der 4Sat ex- und ins TSR importieren und dann testen.
Das mache ich dann ab nächsten Montag ganz in Ruhe zu Hause, habe aber eine "Erfolgsgrafik" angehängt.

Danke, Pav, für deine Arbeit und eine passende Lösung!

Gruß vom Solluh
![TSR_laeuft](https://user-images.githubusercontent.com/42142710/102106048-66dc5480-3e30-11eb-9c61-06f2162cccaf.png)

**Comment by todrees1967** [comment]
Hi, Docker ist nicht schlecht, nur kann meine DS leider kein Docker. Also wäre eine native Version auf DMS7 wirklich sehr wünschenswert.
Viele Grüße
Torsten

**Comment by Pavion** [comment]
Hi Torsten, welche DS ist es, die DSM7 kann aber kein Docker? 
Generell schließt Docker natürlich keine native Version aus, mehr werde ich sehen, wenn DSM7 offiziell verteilt wird. 
Docker ist halt sehr bequem: keine Sorgen, dass Python-Version nicht passt, ffmpeg nicht installiert ist oder irgendwelche Rechte fehlen...

**Comment by todrees1967** [comment]
Hi, ist die DS415play.

**Comment by solluh** [comment]
Hallo Pavion,
ich teste gerade die 1.5.0 - es funktioniert zwar schon vieles, leider kann aber meine Testausfnahme nicht gespeichert werden, ich habe alle 3 Minuten eine Fehlermeldung.
Zudem ist der Import des EPG irgendwie "zäh", früher hatte ich 2 Wochen EPG, jetzt gerade mal 2 Tage.
Ein LOGFile lege ich bei, falls Du da mal reinsehen möchtest, mit Schreibrechten auf der DS habe ich nur so um mich geschmissen...
Ich wünsche Dir ein frohes und gesundes Weihnachtsfest!
Grüße vom Solluh
[log.txt](https://github.com/Pavion/tvstreamrecord/files/5739360/log.txt)

**Comment by Pavion** [comment]
Hi @solluh und danke für den Zwischenstand. 

Zu Deinem Log:

- Füge bitte http der Liste der ffmpeg-Protokolle hinzu. Meine alte Implementierung für http-Aufnahmen schlägt immer öfter fehl; ab 1.5.1 wird auch hierfür ffmpeg verwendet. Damit sollte es aber klappen.
- Ich empfehle Dir gleich die Version 1.5.1 zu installieren, bzw. den Container ganz zu löschen und neu aus der Repository einzurichten (stelle sicher, dass auch im Log 1.5.1 steht). Erst mit 1.5.1 ist es möglich (und wird bei Docker automatisch gemacht), die Einstellungen in den gleichen Ordner wie Aufnahmen "auszugliedern", womit sie immer erhalten bleiben (jetzt sind sie leider weg, sorry). 
- Generell zu Rechten: Du brauchst keine extra Schreibrechte, wenn Du mit Docker arbeitest. Angenommen, Du hast bereits einen öffentlichen Ordner `/volume1/video`, dann sollte es reichen, wenn Du bei der Container-Einrichtung diesen Ordner wählst und ihn dann mit dem internen Pfad `/volume1/common/` verknüpfst. Mehr ist nicht nötig. 
- Das mit EPG liegt halt an der Quelle... vielleicht machen sie gerade Ferien!? 🙂 Wird sicherlich wieder. 
- Die eine `Traceback...`-Fehlermeldung ist unkritisch und wird ab 1.5.2 behoben
- "Possibly corrupted XML file"-Fehlermeldung ist unkritisch und wird ab 1.5.2 in neuer Version richtig als Info `skipping empty file` angezeigt

Frohe Weihnachten auch Dir! 
BR Pav

**Comment by solluh** [comment]
Hallo Pavion,

was für ein Service! :-)

Ich habe die 1.5.1 installiert und nun schreibt er ins Verzeichnis zwar die Datenbank, aber ansonsten habe ich wieder Fehlermeldungen. In der DSwird keine .ts-Datei angelegt, auch nicht mal wie vorhin ganz viele mit der Größe null.
Interessant ist auch, dass die Tombea-Status-Seite von der 4Sat-Netstream keine Verbindung anzeigt, vorhin hatte ich noch einen Stream mit 0.000 kB die Sekunde...
http steht als Stream-Protokoll ja nun drin (das hast Du ja eingebaut), muss ich noch etwas anderes einstellen?
Im Protokoll steht etwas von 'Cannot map stream #0:9 - unsupported type. ...' (12:32:32 Uhr).

Nochmals Dank!

Solluh
[log (1).txt](https://github.com/Pavion/tvstreamrecord/files/5739595/log.1.txt)

**Comment by solluh** [comment]
Nachtrag:
Auf der Elgato-Statusseite wird kurz angezeigt, dass ein Stream gestartet wird (ca. 1 Sekunde), danach ist's wieder aus.

**Comment by Pavion** [comment]
Eins oder alles davon sollte klappen, der Reihe nach: 💡 
- versuche bitte die Erweiterung von `ts` auf `mp4` umzustellen (sollte ich auch mal zum Standard machen)
- füge als ffmpeg Parameter folgendes hinzu: -ignore_unknown:
`-loglevel fatal -map 0 -c copy -ignore_unknown` 
- oder versuche `-map 0` herauszunehmen
- oder ändere bitte in `loglevel error`, um mehr Ausgabe zu sehen

**Comment by solluh** [comment]
Alles gemacht. Keine Besserung. :-(
Neuer Hinweis im Log:
'Invalid data found when processing input'
Loglevel ist jetzt "error".

**Comment by Pavion** [comment]
Also auch die Dateierweiterung? :(
Werden immer noch keine Dateien erzeugt?  
Ggfs. Format vorgeben: `-f mp4`, `-f rtsp` oder `-f mpegts`
Hab noch im Internet dazu geschaut und [hier](https://stackoverflow.com/questions/35866447/ffmpeg-invalid-data-found-when-processing-input-h264-to-h265) und [hier](https://superuser.com/questions/1048637/ffmpeg-video-recording-freezes-after-invalid-data-found-when-processing-input) was gefunden, was man noch anfügen könnte. 
`-err_detect ignore_err -flags +global_header -map_chapters -1`
Wenn nicht, kannst Du bitte nochmal ein Stück Log schicken? Was hast Du für ein Gerät? Fritz!Cable? 
Bin gerade etwas ratlos, sollte eigentlich ganz easy klappen... :(

**Comment by solluh** [comment]
ich bin jetzt bei den Schwiegereltern - Heiligabend feiern...
sobald ich was sagen kann, mache ich es.
Aber das Problem, dass von der Netstream 4Sat kein Stream erzeugt wird, ist immer noch aktuell...
Herzlichen dank!

**Comment by Pavion** [comment]
Schönen 1. Weihnachtstag 🎄  

Kannst Du bitte auch eine Aufnahme mit folgendem Stream testen (KIKA): 
`http://kikageohls-i.akamaihd.net/hls/live/1006268/livetvkika_de/master.m3u8`

Da ich aktuell kein Gerät selbst habe (ich hatte auch mal Netstream), teste ich immer an diesem Stream. Dieser läuft bei mir mit Standardeinstellungen ohne Abbrüche. 

Ich nehme an, mit DSM6 hat alles ohne Probleme funktioniert? Hast Du seitdem etwas anderes verändert? Netzwerkanbindung, Firmware o.Ä.? Ist die Systemauslastung ggfs. zu hoch (in Docker-Übersicht zu sehen)?

Vielen Dank für Dein Feedback, Testen und Deine wohl noch unverdiente Spende, und sorry, dass es doch nicht auf Anhieb klappte. Eigentlich ist ffmpeg eine extrem mächtige und bekannte Bibliothek, die fast alles können soll, deswegen greifen solche Tools wie meins gern darauf zurück. Bei der Vielzahl der Stream-Geräte und -Anbieter heutzutage klappt dann doch mal was nicht :(

**Comment by solluh** [comment]
Auch Dir einen schönen Weihnachtstag, allen anderen Lesern natürlich auch!

Wo soll ich die URL eingeben, damit die Aufnahme von KIKA durchgeführt wird? Ich habe das leider nicht herausfinden können...

Mit DSM 6 ohne Docker lief alles problemfrei. Und für meine lange erfolgreiche Nutzung Deines Programmes habe ich auch die Spende gesandt. Und dafür, dass Du selbst an Weihnachten für die Community (so bezeichne ich mich heute einfach mal) da bist. Verändert habe ich nichts, außer natürlich das Upgrade auf die 7.0. Die Netstream hat kein Update gemacht (macht die ja nie...) und die Systemauslastung liegt bei beinahe null. Auch beim Aufnahmeversuch.  Alles ist per LAN per fester IP miteinander verbunden, ich nutze eine FritzBox 7580.

Mit der tvstreamrecord 1.5.0 hatte ich auf meiner NAS wenigstens noch die leeren Dateien von den Versuchen, die TS-Datei zu schreiben, seit der 1.5.1 sind selbst die nicht mehr zu sehen.

Auf der Seite des Netsream sehe ich (zur Zeit läuft eine Aufnahme per eyeTV) folgendes:

Elgato DVB>IP Server 1.1.0-402r1, Feb 19 2015, 17:49:21
Name: EyeTV Netstream 4Sat (143)
System Status: {"CpuInfo":{"CPUs":1,"Idle":95,"Io":0,"Irq":0,"Nice":0,"Sirq":2,"Sys":1,"Usr":0}}
Board ID: 1
Streams: 4
(# Initialized Type Available Connected Active StreamID Setup Receiving Lock Transcoding TSPacketsReceived rate index sessionID [clientInfo])
#1: 1 4 1 1 1 100 0 1 1 0 3657966 4.431Mbps 2E9D0592 192.168.178.13
#2: 1 4 1 0 0 -1 0 0 0 0 0
#3: 1 4 1 0 0 -1 0 0 0 0 0
#4: 1 4 1 0 0 -1 0 0 0 0 0
Users:
[
    {
        "Frontend":1,
        "IpAddress":"192.168.178.13",
        "MacAddress":"f4:0f:24:30:fe:ab",
        "MachineName":"************",
        "SessionId":"2E9D0592",
        "UserName":"*********"
    }
]
LNBs:
[
    {
        "Mode":"Quad"
    },
...

Wen ich eine Aufnahme mit tvstreamrecord starte, ist kein User aktiv, nur ganz kurz am Anfang, sehe ich die IP-Daresse der NAS. Ich habe die Netstream auch schon mal neu gestartet.

Anbei noch das LOG seit Neuinstall, ich habe die Parameter der Protokollierung zwischendurch verändert.

Ich grüße herzlich!
[log.txt](https://github.com/Pavion/tvstreamrecord/files/5742168/log.txt)

**Comment by Pavion** [comment]
Mit URL meinte ich, dass Du einfach einen neuen Sender erstellst, diese URL eingibst und eine Aufnahme versuchst :) 
Ich schaue mir Deinen Log morgen früh an und melde mich dann.

**Comment by solluh** [comment]
Das hat funktioniert. KIKA aus dem Netz kann ich aufzeichnen.
Also liegt es wohl an der Kommunikation zur Netstream, hoffentlich finden wir eine Lösung.

**Comment by Pavion** [comment]
Hab heute wieder nachgesehen und langsam werde ich erinnert, dass da tatsächlich was mit Netstream war...
Da es die Geräte aber seit mehreren Jahren eigentlich nicht mehr gibt, fand ich leider nichts neues dazu im Internet. 
Je nachdem, wieviel Aufwand Du noch investieren willst, habe ich noch ein paar Ideen: 

1. Probiere bitte noch diese Sender-Varianten aus (von [hier](http://powerpi.de/forum/viewtopic.php?t=291&start=15)):
```
http://192.168.178.110/?src=1&msys=dvbs2&mtype=8psk&freq=11494.00&sr=22000&pol=h&fec=23&pids=0,16,17,18,20,5102,5104,5106,5101,5105,5100,5101
rtsp://192.168.178.110/?src=1&msys=dvbs2&mtype=8psk&freq=11494.00&sr=22000&pol=h&fec=23&pids=0,16,17,18,20,5102,5104,5106,5101,5105,5100,5101
```

2. Nimm doch bitte wieder "http" aus der Liste der Protokolle raus und versuche wieder ohne ffmpeg eine "klassische Aufnahme" zu tätigen. Dabei wäre interessant:
- ob die Dateien (*immer noch*) erstellt werden,
- ob sie abgespielt werden können (oder etwas anderes enthalten?)
- ob Netstream-Gerät längere Aufnahme signalisiert

3. Falls Du etwas tiefer einsteigen magst, wäre die gesamte ffmpeg-Ausgabe interessant. 

- Falls Du Terminal-Zugang zu Deiner DS freigeschaltet hast und Dich auskennst, kannst Du direkt dort eingeben: 

```
ffmpeg -i 'http://192.168.178.110/?src=1&msys=dvbs2&mtype=8psk&freq=11493.75&sr=22000&pol=h&fec=23&pids=0,16,17,18,20,5102,5103,5104,1170,1176,2171,5108,5172,5106,5101,5105,5100,5101' -y /volume1/common/test.mp4
```

- Falls nicht, kannst Du [ffmpeg](ffmpeg.org) für Dein Desktop-PC herunterladen. Für Windows, hier: 
https://github.com/BtbN/FFmpeg-Builds/releases, Datei `ffmpeg-N-100466-g29cef1bcd6-win64-gpl.zip`.
Im Archiv ist nur `/bin/`-Ordner mit drei exe-Dateien interessant, er kann irgendwohin entpackt werden (z.B. d:\test\bin)

Dann kann ffmpeg aus der CMD-Konsole aufgerufen werden:

```
cd /d d:\test\bin
ffmpeg -i "http://192.168.178.110/?src=1&msys=dvbs2&mtype=8psk&freq=11493.75&sr=22000&pol=h&fec=23&pids=0,16,17,18,20,5102,5103,5104,1170,1176,2171,5108,5172,5106,5101,5105,5100,5101" -y d:\test\test.mp4
```

In jedem Fall kannst Du so die gesamte Ausgabe von ffmpeg sehen und kopieren / Screenshot machen, vielleicht sieht man da die Ursache besser. 

4. Wenn alle Stricke reißen, musst Du Dich bitte etwas gedulden, bis DSM7 ausgerollt wird. Scheinbar komme ich nicht drum herum, eine SPK-Version zu basteln, hoffentlich geht es spätestens dann wieder wie gewohnt.

**Comment by solluh** [comment]
Lieber Pavion (Dein Avatar lässt mich vermuten, dass Du männlichen Geschlechts bist),

es läuft! Dankedankedanke!!!! 😄 

Deine vielen Tipps und Kniffe haben leider auch nicht zum Erfolg geführt. Irgendwann hatte einfach keine Lust mehr und als letzte Möglichkeit einen Reset der Netstream durchgeführt. 
Seitdem kann ich zwar kein eyeTV mehr nutzen (laggt ohne Ende) und die Android-App, mit der ich den Receiver aktualisieren und administrieren könnte, findet das Ding nicht, aber ich habe schon eine Aufnahme durchgeführt.
Die Einstellungen stehen jetzt alle wieder auf Standard, http ist bei der ffmpeg-Unterstützung **nicht** eingetragen.
Einzig die Dateierweiterung habe ich auf mp4 gestellt.

Ich danke Dir für die vielen Denkanstöße und freue mich, dass ich mein Lieblingsprogramm (zusammen mit PLEX) auf meiner NAS wieder ausführen kann! Und ich bin nach Ewigkeiten der einfachen "Nutzung" endlich mal wieder in die "Einrichtung" gekommen, was mir erneut andeutungsweise aufgezeigt hat, wie viel Hirnschmalz, Zeit und Aufwand ein Programmierer wie Du in solche Dinge steckt. Und dann stellt ihr es kostenfrei für alle zur Nutzung ins Netz...

Auch dafür war meine Anerkennung, ich hoffe, dass es angemessen war.

Herzliche Grüße vom Solluh
<img width="828" alt="Bildschirmfoto 2020-12-26 um 20 32 37" src="https://user-images.githubusercontent.com/42142710/103158039-c6841980-47b9-11eb-8d81-468d56b7a731.png">
1. Zeile: Aufnahme läuft gerade
2. Zeile: Testaufnahme

**Comment by Pavion** [comment]
Hallo zusammen! 

Nun habe auch ich zu DSM7 migriert und freue mich, Euch die neue Version 1.6.0 für DSM7 vorzustellen:

https://github.com/Pavion/tvstreamrecord/releases/tag/1.6.0

Da sie nun ein paar Eigenheiten hat, lest bitte die Beschreibung vor der Installation. 
Würd' mich über Eure Rückmeldung freuen! 

Pav
