### ISSUE TITLE
Support for linux/arm64?

### ISSUE THREAD

**Issue by mbaiti** [Pavion/tvstreamrecord#55]
Hi Pavion,

Are there any plans to support OS/ARCH: linux/arm64 in future?
I think that would make some Raspberry users very happy, including me.

Thanks!

**Comment by Pavion** [comment]
Hi there! You can use this package with any system capable of running Python (including Pi).

**Comment by Pavion** [comment]
Just to elaborate: download the latest release or clone the master and extract all files into any directory. 
Run `python tvstreamrecord.py` as daemon with any Python > 2.7 (and < 3 if using an old http device like NetStream).

**Comment by mbaiti** [comment]
I tried it with docker-compose on Portainer and the Container log gives me the following error: `standard_init_linux.go:228: exec user process caused: exec format error`

Using this for docker-compose:
`tvstreamrecord:
    image: pavion/tvstreamrecord
    container_name: tvstreamrecord
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /recordings/:/volume1/common/
    ports:
      - 8030:8030`

**Comment by Pavion** [comment]
Oh well I'm not that good with Docker... I assume I'm using x64 linux, which is incompatible with Pi.
The solution stays the same: just use pure Python instead thus greatly reducing overhead and system usage :)

**Comment by Pavion** [comment]
Please note that you must have the corresponding ffmpeg version for your arm64 installed for this package to work.

**Comment by mbaiti** [comment]
Thanks @Pavion 

I try to run everything in Docker containers, therefore install it directly is not an option.
Maybe someone else struggling with the same issue and can provide a solution or maybe you can switch in a future release to a linux which is compatible with arm64.

**Comment by Pavion** [comment]
oh okay, I'll try to look into it at the weekend, perhaps it just needs to be somehow recompiled.

**Comment by Pavion** [comment]
I've managed to recompile my image for other architectures: 

![image](https://user-images.githubusercontent.com/1370084/153611131-c182f8f2-3b36-4050-b0a5-6186d0aab1cb.png)

You should probably delete old image first and pull the latest image, which should automatically select the target architecture:
```
docker run --daemon -v /videos:/volume1/common --publish 8030:8030 --name tvstreamrecord pavion/tvstreamrecord
```

On my Windows x64 I can test it with full SHA:
```
tvstreamrecord>docker run --rm -v C:\coding\test:/volume1/common --publish 8030:8030 --name tvstreamrecord docker.io/pavion/tvstreamrecord:latest@sha256:d442ef71a341fe220bf801daa87ea7374acfb70ccea06945c092012b4bdf9d37
```
CLI:
```
/tsr # uname -m
aarch64
```
At first glance everything works as intended, ffmpeg test record OK. 
Related commit: https://github.com/Pavion/tvstreamrecord/commit/fc896df170d9df9042bda6da25b26a81690377b7

Feedback appreciated!
