### ISSUE TITLE
Docker version 1.6.4 and error http 403

### ISSUE THREAD

**Issue by BruceFeuillette** [Pavion/tvstreamrecord#59]
Hello!
I'm experiencing the same problem than issue #54 but in the Docker version, on a Synology DS918+ running DSM 7.1. 
Last time I've used it was in June and nothing has changed so far, as your image is 10 months old.
I've seen that the docker instance is using python3, issue #54 solution was to run it with python2. How can I do it in the container ?
Cheers

**Comment by BruceFeuillette** [comment]
Ok, I've switched off legacy mode to try.
I have an error stating "Failed to resolve hostname hostname.tld". The FFMPEG command straight in DSM is wroking well.
I'm not sure if there's 2 errors (python3 instead of python2 and a DNS problem) or just one (a DNS problem).

**Comment by Pavion** [comment]
Hi there! 
I've pushed a new Docker image for Python 2.7:
```
pavion/tvstreamrecord:py2
```
You could also install the Synology package instead, which allows for python selection.
You could download the source code and run it manually on any system to further pinpoint your issue 
(just run `somepython tvstreamrecord.py`). 
I hope it helps!

**Comment by BruceFeuillette** [comment]
Thanks!
I didn't manage to get it right with the docker image, I got 4 files full of "error code 1010".
So I get back to the spk version. It works fine, with python2.

**Comment by BruceFeuillette** [comment]
Ok, in fact it only works on non legacy. With legacy mode enable I got a lot of files filled with "error code 1010". Any idea ?

**Comment by Pavion** [comment]
Well legacy works only for http streams, which are just copied byte-wise. 
If your output file is filled with text instead, you're getting an (error) response instead. 
If it worked previously, there was probably some update on the provider side restricting such access (probably some specific User-Agent should be provided [as hinted [here](https://www.awareim.com/forum/viewtopic.php?t=11466) and [here](https://assiste.com/Codes_HTTP/1010.html)]). 
You could try to open your url in your browser and see whether a file is being downloaded.

**Comment by BruceFeuillette** [comment]
I didn't know that it was a HTTP error. :)
FFMPEG works well, manually set, with the same command line that TVStreamRecord uses. 
In the URL, it's a TS file.
I'll stick to normal mode, but sometimes it fails. With legacy mode it was a 100% success.
Thanks for the help!

**Comment by Pavion** [comment]
If  you wish, you can try my latest commit: 
https://github.com/Pavion/tvstreamrecord/compare/master...agent
This should provide an User-Agent for the legacy mode (Python 3 only).

**Comment by BruceFeuillette** [comment]
Awesome !
I modified tvstreamrecord.py and python.ini (to python3) by hand in the @appstore folder. And it works great!
A huge thanks.

**Comment by Pavion** [comment]
Thank you very much for the confirmation and feedback! 
I'll merge the changes and compile a new Docker Py3 release.
